### PR TITLE
Changes for MegaSat Sat>IP Server 2

### PR DESCRIPTION
**Pull request by jmachowinski**
As written in the bug report. Seems we did double work ;-)

### CODE REVIEW

**Comment by rofafor** [comment]
Won't fix.

**Comment by jmachowinski** [comment]
Consider pulling the first patch, it is a general bug fix.

**Comment by rofafor** [comment]
I don't see any functional changes to the current code.

**Comment by jmachowinski** [comment]
In case that the curl_global_init fails, you just give out an message in the 
syslog, but not report that the initialization of the plugin failed. The return
false is missing...

**Comment by jmachowinski** [comment]
To be more precise, the change will make vdr terminate on startup if curl_global_init fails

**Comment by rofafor** [comment]
That's definitely a wrong way to do. A CURL failure here shouldn't prevent any DVB/IPTV/PVRInput operation.

**Pull request closed without merging**
